### ISSUE TITLE
"base" Security Group issue.

### ISSUE THREAD

**Issue by rsankaranarayanan** [philips-software/go-hsdp-api#43]
The below error message is occurring due to the security group.
{"code":400,"description":"CODE: InvalidGroup.NotFound,  MESSAGE: You have specified two resources that belong to different networks."}

By default, the cartel API is adding a "base" security group while creating EC2 instances.  Suppose I add a "base" security group in the "security_groups" group variable. This error message is occurring. I am thinking that the carte API is treating this as a new security group and try to add. It is failing. 

The Example: security_groups = ["XXXX", "base"]

**Comment by loafoe** [comment]
@rsankaranarayanan I will move this ticket to https://github.com/philips-software/terraform-provider-hsdp/issues
